project:
  type: book
  output-dir: _book


book:
  title: "Material Book"
  author: "Marcel Ferreira"
  date: today
  
  
  page-footer:
    left: |
      This book is Marcel Ferreira initiative.
    right: |
      This website was built with <a href="https://quarto.org/">Quarto</a>.
  
  chapters:
    - index.qmd
    - intro.qmd
    
    - part: sequencing_intro.qmd
      chapters:
      - illumina.qmd
      - nanopore.qmd
      
    - part: rbase.qmd
    
    - part: rpackages_intro.qmd
    
    - part: bioinformatics.qmd
      chapters:
      - bioinformatics_files.qmd
    
    - part: ml_intro.qmd
      chapters:
      - ml_theory.qmd

    - references.qmd

bibliography: references.bib

format:
  html:
    theme: simplex
    code-link: true


editor: visual
engine: knitr

